print("  ")
print("  ")
print("     ")
print("    ")
print("          __   ")
print("       __/  \__ ")
print("    __/  \__/  \__ ")
print("   /  \__/  \__/  \ ")
print("   \__/  \__/  \__/ ")
print("      \__/  \__/  ")
print("         \__/   ")
print("    ")
print("    ")
print("     ")
print("   ")
import fzzl
fzzl.fzzl()
